apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  traefik-servicemonitor
  namespace: proxy
  labels:
    app: traefik-prometheus-servicemonitor
spec:
  jobLabel: traefik-metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik-metrics
  endpoints:
  - port: metrics
    path: /metrics