---
- name: Enable required cgroup features.
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory swapaccount=1'
    state: present
  register: cgroup_features

# Theoretically the raspberry pies do not have swap. We can check with:
# ansible all -m ansible.builtin.shell -a 'sudo swapon --show'
# The problem is that in my previous attemps docker was complaining so 
# I activated it to disable the warning.

- name: Reboot immediately if cgroup features changed.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: cgroup_features is changed

- name: Wait for the reboot to complete if cgroup features changed.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: cgroup_features is changed


# https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/tasks/cgroup-features.yml
#The MIT License (MIT)

#Copyright (c) 2015 Jeff Geerling

#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
