# https://github.com/actions/actions-runner-controller/blob/master/charts/actions-runner-controller/values.yaml

syncPeriod: 1m
defaultScaleDownDelay: 5m

#hostNetwork: true
dnsPolicy: Default

authSecret:
  enabled: true
  name: "controller-manager"

metrics:
  serviceMonitor:
    enable: true


podDisruptionBudget:
  enabled: false

certManagerEnabled: true

actionsMetrics:
  serviceMonitor:
    enable: true