{
 "title": "Alerts",
 "description": "Display Alerts from Prometheus. Now with configurable datasource and adjustable severity.",
 "tags": [
  "prometheus",
  "alerts"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "severity", "query": { "query": "label_values(ALERTS,severity)" } },
   { "name": "alertname", "query": { "query": "label_values(ALERTS,alertname)" } }
  ]
 },
 "panels": [
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", alertname != \"Watchdog\" }) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate = \"pending\", alertname != \"Watchdog\" }) by (severity)",
     "legendFormat": "{{s}}"
    }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", alertname != \"Watchdog\", severity=~\"$severity\" }) by (alertname,namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alertname: ${alertname}",
   "type": "state-timeline",
   "description": "details on certain alertname",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", alertname != \"Watchdog\", severity=~\"$severity\", alertname=~\"$alertname\" }",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table - Firing Alerts ",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", alertname != \"Watchdog\", severity=~\"$severity\" }"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\", alertname != \"Watchdog\",severity=~\"$severity\" }) by (alertname)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}