apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vault
spec:
  storageClassName: replicated
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi