apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring.anagno.dev
  namespace: monitoring
spec:
  commonName: monitoring.anagno.dev
  secretName: monitoring.anagno.dev
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - monitoring.anagno.dev
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: monitoring.anagno.dev
  namespace: monitoring
  annotations:
    external-dns.alpha.kubernetes.io/hostname: monitoring.anagno.dev
    external-dns.alpha.kubernetes.io/target: zh.anagno.dev
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`monitoring.anagno.dev`)
      kind: Rule
      services:
        - name: monitoring-grafana
          port: 80
      middlewares:
      - name: security-headers
        namespace: proxy
  tls:
    secretName: monitoring.anagno.dev
    options:
      name: tls-security-headers
      namespace: proxy
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: monitoring.anagno.dev-http
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`monitoring.anagno.dev`)
      kind: Rule
      services:
        - name: monitoring-grafana
          port: 80
      middlewares:
      - name: https-redirect
        namespace: proxy
