apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring.anagno.me
  namespace: monitoring
spec:
  commonName: monitoring.anagno.me
  secretName: monitoring.anagno.me
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - monitoring.anagno.me
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: monitoring.anagno.me
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`monitoring.anagno.me`)
      kind: Rule
      services:
        - name: monitoring-grafana
          port: 80
      middlewares:
      - name: security-headers
        namespace: proxy
      - name: authorization
        namespace: authentication
  tls:
    secretName: monitoring.anagno.me
    options:
      name: tls-security-headers
      namespace: proxy
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: monitoring.anagno.me-http
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`monitoring.anagno.me`)
      kind: Rule
      services:
        - name: monitoring-grafana
          port: 80
      middlewares:
      - name: https-redirect
        namespace: proxy
