# https://github.com/nextcloud/helm/blob/main/charts/nextcloud/values.yaml

ingress:
  enabled: false

phpClientHttpsFix:
  enabled: false
  protocol: https

nextcloud:
  host: locker.anagno.dev
  existingSecret:
    enabled: true
    secretName: nextcloud
    usernameKey: admin-username
    passwordKey: admin-password
    tokenKey: serverinfo_token
  mail:
    enabled: false
    fromAddress: no-reply-anagno-me
    domain: outlook.com
    smtp:
      host: smtp.office365.com
      secure: tls
      port: 587
      authtype: LOGIN
  # PHP Configuration files
  # Will be injected in /usr/local/etc/php/conf.d for apache image and in /usr/local/etc/php-fpm.d when nginx.enabled: true
  phpConfigs: {}
  # IMPORTANT: Will be used only if you put extra configs, otherwise default will come from nextcloud itself
  # Default confgurations can be found here: https://github.com/nextcloud/docker/tree/master/.config
  defaultConfigs:
    # To protect /var/www/html/config
    .htaccess: true
    # Apache configuration for rewrite urls
    apache-pretty-urls.config.php: true
    # Define APCu as local cache
    apcu.config.php: true
    # Apps directory configs
    apps.config.php: true
    # Used for auto configure database
    autoconfig.php: true
    # Redis default configuration
    redis.config.php: false
    # Reverse proxy default configuration
    reverse-proxy.config.php: false
    # S3 Object Storage as primary storage
    s3.config.php: false
    # SMTP default configuration via environment variables
    smtp.config.php: false
    # Swift Object Storage as primary storage
    swift.config.php: false
    # disables the web based updater as the default nextcloud docker image does not support it
    upgrade-disable-web.config.php: true
    # -- adjust openmetrics
    helm-metrics.config.php: true
    # -- imaginary support config
    imaginary.config.php: false

  # Extra config files created in /var/www/html/config/
  # ref: https://docs.nextcloud.com/server/15/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file
  configs: 
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '127.0.0.1',
          1 => '10.0.0.0/8',
        ),
        'overwriteprotocol' => 'https',
        'overwritehost' => 'locker.anagno.dev',
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        'allow_local_remote_servers' => true,
      );

  #extraEnv:
    #- name: SMTP_NAME
    #  value: no-reply-anagno-me@outlook.com
    #- name: SMTP_PASSWORD
    #  valueFrom:
    #    secretKeyRef:
    #      name: no-reply-mail
    #      key: password

resources:
  requests:
    cpu: 500m
    memory: 512Mi

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: "nextcloud-database-cluster-rw"
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-postgresql
    usernameKey: username
    passwordKey: password

mariadb:
  enabled: false
postgresql:
  enabled: false
externalRedis:
  enabled: false
redis:
  enabled: false
collabora:
  enabled: false

cronjob:
  # During the initial deployment, disable it.
  # If the instance is not ready it will cause errors
  enabled: true
  type: sidecar
  sidecar:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  existingClaim: nextcloud-pvc

livenessProbe:
  # TODO:remember to disable during upgrades
  enabled: true
  #enabled: true
  initialDelaySeconds: 60
  periodSeconds: 60
  timeoutSeconds: 15
readinessProbe:
  # TODO:remember to disable during upgrades
  enabled: true
  #enabled: true
  initialDelaySeconds: 60
  periodSeconds: 60
  timeoutSeconds: 15
startupProbe:
  # TODO:remember to disable during upgrades
  enabled: true
  #enabled: true

hpa:
  # TODO:remember to disable during upgrades
  enabled: true
  cputhreshold: 80
  minPods: 1
  maxPods: 2

dnsConfig:
  options:
    - name: ndots
      value: "1"

imaginary:
  enabled: false

metrics:
  enabled: false
  replicaCount: 1

prometheus:
  serviceMonitor:
    enabled: false
