apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: locker-redis-master-vpa
  namespace: locker
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: locker-redis-master
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: locker-postgresql-vpa
  namespace: locker
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: locker-postgresql
  updatePolicy:
    updateMode: "Auto"