---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: library.anagno.me
  namespace: library
spec:
  commonName: library.anagno.me
  secretName: library.anagno.me
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - library.anagno.me
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: library.anagno.me-opds
  namespace: library
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`library.anagno.me`) && PathPrefix(`/opds`)"
      kind: Rule
      priority: 10 
      services:
        - name: calibre-service
          port: 80
      middlewares:
      - name: security-headers
        namespace: proxy
      - name: authorization-basic
        namespace: authentication
  tls:
    secretName: library.anagno.me
    options:
      name: tls-security-headers
      namespace: proxy
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: library.anagno.me
  namespace: library
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`library.anagno.me`)
      kind: Rule
      priority: 1 
      services:
        - name: calibre-service
          port: 80
      middlewares:
      - name: security-headers
        namespace: proxy
      - name: authorization
        namespace: authentication
  tls:
    secretName: library.anagno.me
    options:
      name: tls-security-headers
      namespace: proxy
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: library.anagno.me-http
  namespace: library
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`library.anagno.me`)
      kind: Rule
      services:
        - name: calibre-service
          port: 80
      middlewares:
      - name: https-redirect
        namespace: proxy
---  