apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: news
  labels:
    app: freshrss-server
spec:
  selector:
    matchLabels:
      app: freshrss-server
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: freshrss-server
    spec:
      dnsPolicy: Default
      containers:
      - name: freshrss-server
        image: freshrss/freshrss:1.26.3
        imagePullPolicy: IfNotPresent
        env:
        - name: TRUSTED_PROXY
          value: "10.0.0.0/8"
        - name: CRON_MIN
          value: "17,47"
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - mountPath: /var/www/FreshRSS/data
            name: data
            readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: news-data
            readOnly: false
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: news-vpa
  namespace: news
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: freshrss
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        maxAllowed:
          cpu: 1
          memory: 1024Mi
---