---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: news.anagno.dev
  namespace: news
spec:
  commonName: news.anagno.dev
  secretName: news.anagno.dev
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - news.anagno.dev
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: override-headers
  namespace: news
spec:
  headers:
    contentSecurityPolicy: "default-src 'self'; img-src https: data:; object-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: news.anagno.dev-api
  namespace: news
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`news.anagno.dev`) && PathPrefix(`/api`)"
      kind: Rule
      priority: 10 
      services:
        - name: freshrss-service
          port: 80
      middlewares:
      - name: override-headers
        namespace: news
      - name: security-headers
        namespace: proxy
  tls:
    secretName: news.anagno.dev
    options:
      name: tls-security-headers
      namespace: proxy
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: news.anagno.dev
  namespace: news
  annotations:
    external-dns.kubernetes.io/hostname: news.anagno.dev
    external-dns.kubernetes.io/target: zh.anagno.dev
    kubernetes.io/ingressClassName: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`news.anagno.dev`)
      kind: Rule
      priority: 1 
      services:
        - name: freshrss-service
          port: 80
      middlewares:
      - name: override-headers
        namespace: news
      - name: security-headers
        namespace: proxy
  tls:
    secretName: news.anagno.dev
    options:
      name: tls-security-headers
      namespace: proxy
