apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-data
  namespace: news
spec:
  storageClassName: replicated
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi