# https://github.com/longhorn/charts/blob/master/charts/longhorn/values.yaml

service:
  ui:
    type: ClusterIP

persistence:
  defaultClassReplicaCount: 3
  reclaimPolicy: Delete

defaultSettings:
  defaultDataPath: /media/storage/
  createDefaultDiskLabeledNodes: false
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 15
  replicaAutoBalance: "least-effort"
  defaultDataLocality: "disabled"
  snapshotDataIntegrity: "enabled"
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  concurrentReplicaRebuildPerNodeLimit: 1
  allowNodeDrainWithLastHealthyReplica: "false"
  orphanAutoDeletion: "true"
  # https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/
  # https://github.com/longhorn/longhorn/issues/1691
  guaranteedEngineManagerCPU: 20
  guaranteedReplicaManagerCPU: 20
