apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: load-balancer
spec:
  addresses:
  - 192.168.179.230-192.168.179.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: load-balancer
spec:
  ipAddressPools:
  - default
---