# https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml

configInline:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 192.168.179.230-192.168.179.250

prometheus:
  podMonitor:
    enabled: true

controller:
  image:
    pullPolicy: IfNotPresent
  # For monitoring later the metallb deployment
  prometheus:
    serviceMonitor:
      enabled: true

speaker:
  image:
    pullPolicy: IfNotPresent
# For monitoring later the metallb deployment
  prometheus:
    serviceMonitor:
      enabled: true