apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup
  namespace: test-database
spec:
  cluster:
    name: database-cluster
  # https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format
  schedule: '0 0 * * * *'  
  backupOwnerReference: self
  method: volumeSnapshot
  immediate: true