apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-database
  namespace: authorization
  labels:
    app: authentik-database
spec:
  storageClassName: replicated
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis
  namespace: authorization
  labels:
    app: authentik-redis
spec:
  storageClassName: replicated
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
