# https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml

image:
  repository: ghcr.io/goauthentik/server
  #tag: 2023.2.2


ingress:
  enabled: false

authentik:
  avatars: none
  email:
    host: "smtp-mail.outlook.com"
    port: 587
    username: "no-reply-anagno-me@outlook.com"
    use_tls: true
    use_ssl: false
    timeout: 30
    from: "no-reply-anagno-me@outlook.com"
  postgresql:
    name: "authentik"
    user: "authentik"

# we have to create first the ingressroute, so the secrets are available
# https://goauthentik.io/docs/core/certificates#web-certificates
volumes:
  - name: web-keys
    secret:
      secretName: auth-anagno-dev-cert
      items:
      - key: tls.crt
        path: auth.anagno.dev.pem
      - key: tls.key
        path: auth.anagno.dev.key

volumeMounts:
  - name: web-keys
    readOnly: true
    mountPath: "/certs"

envValueFrom:
  AUTHENTIK_SECRET_KEY:
    secretKeyRef:
      name: authentik-generall
      key: secret-key
  AK_ADMIN_PASS:
    secretKeyRef:
      name: authentik-generall
      key: ak-admin-pass
  AUTHENTIK_EMAIL__PASSWORD:
    secretKeyRef:
      name: no-reply-mail
      key: password
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: authentik-database
      key: postgresql-password
  AUTHENTIK_REDIS__PASSWORD:
    secretKeyRef:
      name: authentik-redis
      key: redis-password

service:
  enabled: true
  type: ClusterIP
  port: 80
  name: http
  protocol: TCP

prometheus:
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 3s
  rules:
    create: true

postgresql:
  enabled: true
  postgresqlUsername: "authentik"
  postgresqlDatabase: "authentik"
  existingSecret: authentik-database
  persistence:
    enabled: true
    existingClaim: authentik-database

redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: "authentik-redis"
  master:
    persistence:
      enabled: true
      existingClaim: authentik-redis

# https://github.com/goauthentik/helm/blob/480a5546b6d6b3d089e14dea357d9726439086fb/charts/authentik/ci/manfiests/blueprint.yaml
# https://github.com/goauthentik/helm/blob/480a5546b6d6b3d089e14dea357d9726439086fb/charts/authentik/ci/ct-values.yaml#L39
# https://github.com/goauthentik/helm/issues/127
# https://github.com/FruitCast/authentik-manager
# https://github.com/dsluijk/authentik-operator
blueprints: []