 
apiVersion: v1
kind: Service
metadata:
  name: grigoris-service
  namespace: proxy
spec:
  type: ExternalName
  externalName: 192.168.1.149
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grigoris-http
  namespace: proxy
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`zuri.greganagno.com`)
      kind: Rule
      services:
        - name: grigoris-service
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: grigoris
  namespace: proxy

spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`zuri.greganagno.com`)
      services:
        - name: grigoris-service
          port: 443
  tls:
    passthrough: true
