---
- name: Update node
  hosts: all
  serial: 1
  become: yes
  tasks:
    - name: Drain node from cluster
      kubernetes.core.k8s_drain:
        state: drain
        name: '{{ inventory_hostname }}'
        delete_options:
          force: yes

    - name: Upgrade the OS (apt-get update)
      apt:
        update_cache: yes
        upgrade: dist

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot immediately if required from updates
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: reboot_required_file.stat.exists

    - name: Wait for the reboot to complete if updates were made.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: reboot_required_file.stat.exists

    - name: Restore node to cluster
      kubernetes.core.k8s_drain:
        state: cordon
        name: '{{ inventory_hostname }}'