apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pantheon.anagno.dev
  namespace: pantheon
spec:
  commonName: pantheon.anagno.dev
  secretName: pantheon.anagno.dev
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - pantheon.anagno.dev
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pantheon.anagno.dev
  namespace: pantheon
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pantheon.anagno.dev`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
      middlewares:
      - name: security-headers
        namespace: proxy
  tls:
    secretName: pantheon.anagno.dev
    options:
      name: tls-security-headers
      namespace: proxy
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pantheon.anagno.dev-http
  namespace: pantheon
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pantheon.anagno.dev`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
      middlewares:
      - name: https-redirect
        namespace: proxy
