apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
  namespace: pantheon
spec:
  storageClassName: replicated
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---