apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: portainer-vpa
  namespace: pantheon
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: portainer
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        maxAllowed:
          cpu: 1
          memory: 512Mi
