apiVersion: apps/v1 
kind: Deployment
metadata:
  namespace: general
  name: ddns-updater-anagno-dev
spec:
  selector:
    matchLabels:
      app: ddns
  replicas: 1
  template:
    metadata:
      labels:
        app: ddns
    spec:
      containers:
      - name: ddns
        image: anagno/gandi-ddns:0.3
        env:
        - name: DOMAIN
          value: "anagno.dev"
        - name: SUBDOMAIN
          value: "zh"
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: gandi
              key: API_KEY
      dnsPolicy: Default
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: ddns-updater-anagno-dev-vpa
  namespace: general
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: ddns-updater-anagno-dev
  updatePolicy:
    updateMode: "Auto"
