apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karakeep-servicemonitor
  namespace: bookmarks
spec:
  namespaceSelector:
    matchNames:
    - bookmarks
  selector:
    matchLabels:
      app.kubernetes.io/instance: karakeep
      app.kubernetes.io/name: karakeep
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    bearerTokenSecret:
      name: karakeep
      key: NEXTAUTH_SECRET
