apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: vcs-postgresql-vpa
  namespace: vcs
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: vcs-postgresql
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: vcs-gitea-vpa
  namespace: vcs
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: vcs-gitea
  updatePolicy:
    updateMode: "Auto"
