apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrents-pvc
  namespace: torrents
spec:
  # They are not important data
  storageClassName: unreplicated
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: torrents
spec:
  storageClassName: replicated
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50M
