apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: torrents
  labels:
    app: transmission-server
spec:
  selector:
    matchLabels:
      app: transmission-server
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission-server
    spec:
      dnsPolicy: Default    
      containers:
      - name: transmission-server
        image: lscr.io/linuxserver/transmission:latest
        imagePullPolicy: IfNotPresent   
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        ports:
          - name: webgui
            containerPort: 9091
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            #cpu: 500m
            memory: 100Mi
        volumeMounts:
          - mountPath: /downloads
            name: transmission-storage
          - mountPath: /config
            name: transmission-config            
      volumes:
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-config
            readOnly: false
        - name: transmission-storage
          persistentVolumeClaim:
            claimName: torrents-pvc
            readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-server
  namespace: torrents
  labels:
    app: samba-server
spec:
  selector:
    matchLabels:
      app: samba-server
  replicas: 1
  template:
    metadata:
      labels:
        app: samba-server
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: samba-server
        image: dperson/samba:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: USERID
            value: "1000"
          - name: GROUPID
            value: "1000"
        args:
          # disable recycle bin
          - -r
          - -s
          - "data;/data;yes;yes;no;all;none;anagno"
          - -u
          - "anagno;anagno"
        ports:
          - name: netbios
            containerPort: 139
          - name: smb
            containerPort: 445
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            #cpu: 500m
            memory: 512Mi
        volumeMounts:
          - mountPath: /data
            name: samba-storage
      volumes:
        - name: samba-storage
          persistentVolumeClaim:
            claimName: torrents-pvc
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: samba-server-service
  namespace: torrents
  labels:
    app: samba-server-service
spec:
  ports:
  - name: netbios
    port: 139
    protocol: TCP
    targetPort: 139
  - name: smb
    port: 445
    protocol: TCP
    targetPort: 445        
  selector:
    app: samba-server
  type: LoadBalancer
  loadBalancerIP: 192.168.179.235
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-server-service
  namespace: torrents
  labels:
    app: transmission-server
spec:
  ports:
  - name: dashboard
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: transmission-server
  sessionAffinity: None
---

# Referemces:
# https://github.com/ehough/docker-nfs-server/issues/25
# https://github.com/ehough/docker-nfs-server/issues/6
# https://github.com/dperson/samba/issues/236
# https://github.com/dperson/samba
# https://github.com/sahsu/transmission-blocklist/releases/latest/download/blocklist.gz
# https://westzq1.github.io/k8s/2019/06/28/nfs-server-on-K8S.html
