# https://github.com/mittwald/kubernetes-replicator/blob/master/deploy/helm-chart/kubernetes-replicator/values.yaml

replicationEnabled:
  secrets: true
  configMaps: true
  roles: true
  roleBindings: true
  serviceAccounts: true
