# https://github.com/kubeops-tools/kubed/blob/v0.12.0/charts/kubed/values.yaml

# Number of Kubed operator replicas to create (only 1 is supported)
replicaCount: 1

operator:
  registry: appscode
  repository: kubed
  tag: v0.12.0

# Container image pull policy
imagePullPolicy: IfNotPresent

config:
  clusterName: olympus
