apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-database
  namespace: authentication
  labels:
    app: authelia-mariadb
spec:
  storageClassName: replicated
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
